In [5]:
import sys
import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image

frames = []
sprite = Image.new("L", (103*8150,103))
for j in range(8150):
    i = j+1
    image = Image.open(os.path.join(sys.path[0], "./frames/web/"+str(i)+".png"))
    sprite.paste(image, (j*103, 0))
sprite.save("./frames/sprite.png")

In [36]:
adf

,frame,bright_w,valence_w,max_w,bright_t,valence_t,max_t,bright_c,valence_c,max_c,bright_f,valence_f,max_f,bright_s,valence_s,max_s
0,1.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0
1,2.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0
2,3.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0
3,4.0,0.214669,129.0,3.0,0.011813,30.0,3.0,0.001886,9.0,3.0,0.000272,6.0,3.0,0.001208,65.0,10.0
4,5.0,0.214583,134.0,3.0,0.011764,30.0,3.0,0.001940,9.0,7.0,0.000278,7.0,7.0,0.001183,65.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8145,8146.0,0.210809,103.0,3.0,0.011557,37.0,3.0,0.001839,8.0,3.0,0.000265,6.0,3.0,0.001054,52.0,3.0
8146,8147.0,0.209990,105.0,3.0,0.011499,48.0,3.0,0.001871,10.0,3.0,0.000272,9.0,3.0,0.001061,52.0,3.0
8147,8148.0,0.209422,107.0,3.0,0.011450,32.0,3.0,0.001824,9.0,3.0,0.000268,8.0,3.0,0.001061,51.0,3.0
8148,8149.0,0.210306,106.0,3.0,0.011517,40.0,3.0,0.001843,9.0,3.0,0.000269,7.0,3.0,0.001056,51.0,3.0
8149,8150.0,0.210089,105.0,3.0,0.011519,40.0,3.0,0.001839,9.0,3.0,0.000265,4.0,3.0,0.001062,52.0,3.0

In [11]:
df

      frame     whole    circle     torus     focus
0         1  0.000000  0.000000  0.000000  0.000000
1         2  0.000000  0.000000  0.000000  0.000000
2         3  0.000000  0.000000  0.000000  0.000000
3         4  0.214669  0.001886  0.011813  0.000272
4         5  0.214583  0.001940  0.011764  0.000278
...     ...       ...       ...       ...       ...
8181   8182  0.065621  0.000588  0.003623  0.000086
8182   8183  0.065621  0.000588  0.003623  0.000086
8183   8184  0.065621  0.000588  0.003623  0.000086
8184   8185  0.065621  0.000588  0.003623  0.000086
8185   8186  0.065621  0.000588  0.003623  0.000086

[8186 rows x 5 columns]